interface Env {
	NATIVE_APP_ORIGINS?: string;
	TURNSTILE_ALLOWED_HOSTNAMES?: string;
	WEB_PUSH_VAPID_PUBLIC_KEY?: string;
	WEB_PUSH_VAPID_PRIVATE_KEY?: string;
	WEB_PUSH_VAPID_SUBJECT?: string;
	WELCOME_CLAIM_HASH_SECRET?: string;
}
